site_name: Портфолио / Лабы

theme:
  name: material

  palette:
    scheme: slate
    primary: black
    accent: indigo

  font:
    code: Roboto Mono

  features:
    - navigation.tabs

repo_url: https://github.com/slw0000

nav:
  - Главная: index.md
  - Об авторе: author.md
  - Лабораторные работы:
      - Лабораторная 1: labs/lab-01.md
